/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSH */

#ifndef _Included_JSH
#define _Included_JSH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSH
 * Method:    readLine
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JSH_readLine
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
